### ISSUE TITLE
Parameters meaning.

### ISSUE THREAD

**Issue by ujjwaldel** [yclicc/FLAME-python#1]
Could you better explain the parameters of flame.py, what do they mean.
_cluster_neighbors=5, iteration_neighbors=5, max_iter=np.inf, eps=1e-10, thd=-2,_ especially these ones.

**Comment by yclicc** [comment]
Sorry for the late reply:

If you haven't already done so please watch [this video](https://vimeo.com/78348227) (or consult the paper in the readme) which explains roughly how the algorithm works.

The cluster_neighbors determines how many nearest neighbors are used in the initial density calculation (in the video it is 3). Once the densities have been calculated any point with density less than the mean density plus thd standard deviations (which defaults to -2) is declared to be an outlier. The cluster support objects are then those which have higher density than all their nearest neighbors. Finally, the iteration_neighbors number of nearest neighbors to each point is those points which pass cluster membership probability to that point each iteration. Then the algorithm iterates until either max_iter (by default infinity) is reached or the cluster membership probabilities don't change by more than eps (by default 10^-10). Does that clarify things?

**Comment by ujjwaldel** [comment]
yep, thanks.
